framework: mocha
src_files:
    - node_modules/chai/chai.js
    - lib/**/*.js
    - tests/setup.js
    - tests/test_*.js
watch_files:
    - lib/**/*.js
    - tests/**/*.js
launchers:
    node:
        command: node_modules/mocha/bin/mocha tests/test_*.js -R tap
        protocol: tap
launch_in_dev:
    - node
